# Generated by Django 4.2.27 on 2025-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the item", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Detailed description of the item")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the item was created"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-created_at"],
            },
        ),
    ]
