# Generated by Django 5.2.9 - Split migration: Collection model

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 2: RAG Collection Model

    Creates the Collection model for RAG (Retrieval Augmented Generation).
    Collections store documents with embeddings for context-aware translations.
    """

    dependencies = [
        ("api", "0001_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=191, unique=True)),
                ("description", models.TextField()),
                (
                    "embedding_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("gemini", "Google Gemini"), ("ollama", "Ollama (Local)")],
                        default="gemini",
                        max_length=100,
                    ),
                ),
                ("embedding_model", models.CharField(default="text-embedding-004", max_length=100)),
                ("embedding_dimensions", models.PositiveIntegerField(default=768)),
                ("completion_model", models.CharField(default="gemini-2.0-flash-exp", max_length=100)),
                (
                    "chunking_strategy",
                    models.CharField(
                        choices=[
                            ("fixed-length", "Fixed Length"),
                            ("window", "Window"),
                            ("no-chunking", "No Chunking"),
                        ],
                        default="fixed-length",
                        max_length=100,
                    ),
                ),
                ("chunk_length", models.PositiveIntegerField(blank=True, default=1000, null=True)),
                ("chunk_overlap", models.PositiveIntegerField(blank=True, default=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
