# Generated by Django 4.2.27 on 2025-12-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("patient_doctor", "Patient-Doctor"), ("general", "General")],
                        default="patient_doctor",
                        max_length=20,
                    ),
                ),
                ("patient_language", models.CharField(default="en", max_length=50)),
                ("doctor_language", models.CharField(default="en", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sender_type",
                    models.CharField(choices=[("patient", "Patient"), ("doctor", "Doctor")], max_length=10),
                ),
                ("original_text", models.TextField()),
                ("original_language", models.CharField(max_length=50)),
                ("translated_text", models.TextField(blank=True, null=True)),
                ("translated_language", models.CharField(blank=True, max_length=50, null=True)),
                ("has_image", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("image_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="api.chatroom"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
