# Generated by Django 4.2.27 on 2025-12-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_chatroom_alter_item_options_item_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=191, unique=True)),
                ("description", models.TextField()),
                (
                    "embedding_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("gemini", "Google Gemini")], default="gemini", max_length=100
                    ),
                ),
                ("embedding_model", models.CharField(default="text-embedding-004", max_length=100)),
                ("embedding_dimensions", models.PositiveIntegerField(default=768)),
                ("completion_model", models.CharField(default="gemini-2.0-flash-exp", max_length=100)),
                (
                    "chunking_strategy",
                    models.CharField(
                        choices=[
                            ("fixed-length", "Fixed Length"),
                            ("window", "Window"),
                            ("no-chunking", "No Chunking"),
                        ],
                        default="fixed-length",
                        max_length=100,
                    ),
                ),
                ("chunk_length", models.PositiveIntegerField(blank=True, default=1000, null=True)),
                ("chunk_overlap", models.PositiveIntegerField(blank=True, default=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="api.collection"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
