# Generated by Django 5.2.9 - Split migration: ChatRoom model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 3: ChatRoom Model

    Creates the ChatRoom model for patient-doctor conversations.
    Each room has language settings and can link to a RAG collection.
    """

    dependencies = [
        ("api", "0002_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("patient_doctor", "Patient-Doctor"), ("general", "General")],
                        default="patient_doctor",
                        max_length=20,
                    ),
                ),
                ("patient_language", models.CharField(default="en", max_length=50)),
                ("doctor_language", models.CharField(default="en", max_length=50)),
                ("patient_name", models.CharField(blank=True, help_text="Patient name for context", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rag_collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="RAG collection for cultural and medical context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_rooms",
                        to="api.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
