# Generated by Django 4.2.27 on 2025-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_collection_collectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="audio_duration",
            field=models.FloatField(blank=True, help_text="Duration in seconds", null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="chat_audio/"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="audio_transcription",
            field=models.TextField(blank=True, help_text="Transcribed text from audio"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="has_audio",
            field=models.BooleanField(default=False),
        ),
    ]
