# Generated by Django 5.2.9 - Split migration: ChatMessage model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 4: ChatMessage Model

    Creates the ChatMessage model for storing messages in chat rooms.
    Supports text, audio, and image messages with translations.
    """

    dependencies = [
        ("api", "0003_chatroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sender_type",
                    models.CharField(choices=[("patient", "Patient"), ("doctor", "Doctor")], max_length=10),
                ),
                ("original_text", models.TextField()),
                ("original_language", models.CharField(max_length=50)),
                ("translated_text", models.TextField(blank=True, null=True)),
                ("translated_language", models.CharField(blank=True, max_length=50, null=True)),
                ("has_image", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("image_description", models.TextField(blank=True, null=True)),
                ("has_audio", models.BooleanField(default=False)),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="chat_audio/")),
                ("audio_duration", models.FloatField(blank=True, help_text="Duration in seconds", null=True)),
                ("audio_transcription", models.TextField(blank=True, help_text="Transcribed text from audio")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="api.chatroom"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
