# Generated by Django 5.2.9 - Split migration: CollectionItem model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 5: CollectionItem Model

    Creates the CollectionItem model for storing documents in RAG collections.
    Each item has content, metadata, and vector embeddings for similarity search.
    """

    dependencies = [
        ("api", "0004_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="api.collection"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
