# Generated by Django 4.2.27 on 2025-12-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_chatmessage_audio_duration_chatmessage_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="patient_name",
            field=models.CharField(blank=True, help_text="Patient name for context", max_length=200),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="rag_collection",
            field=models.ForeignKey(
                blank=True,
                help_text="RAG collection for cultural and medical context",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_rooms",
                to="api.collection",
            ),
        ),
    ]
