# Generated by Django 5.2.9 - Split migration: UserProfile model

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 6: UserProfile Model

    Creates the UserProfile model for storing additional user information.
    Includes cultural background, medical conditions, and communication preferences.
    """

    dependencies = [
        ("api", "0005_collectionitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cultural_background", models.TextField(blank=True, help_text="Cultural background and preferences")),
                (
                    "communication_preferences",
                    models.JSONField(blank=True, default=dict, help_text="Communication style preferences"),
                ),
                ("medical_conditions", models.TextField(blank=True, help_text="Known medical conditions")),
                ("allergies", models.TextField(blank=True, help_text="Known allergies")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
