# Generated by Django 5.2.9 - Split migration: Item model (legacy)

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 7: Item Model (Legacy)

    Creates the Item model - a simple model for testing/demo purposes.
    This can be removed in production if not needed.
    """

    dependencies = [
        ("api", "0006_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
