# Generated by Django 5.2.9 - Split migration: Collection type fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 8: Collection Type Fields

    Adds collection_type, is_global, and chat_room fields to Collection.
    This enables the two-tier RAG system:
    - Knowledge Base: Global reference data for all translations
    - Patient Context: Per-patient details linked to specific chat rooms
    """

    dependencies = [
        ("api", "0007_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                choices=[("knowledge_base", "Knowledge Base"), ("patient_context", "Patient Context")],
                default="knowledge_base",
                help_text="Knowledge Base: global reference data. Patient Context: per-chat patient details.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="is_global",
            field=models.BooleanField(
                default=True,
                help_text="Global collections are used for all translations. Non-global are chat-specific.",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                help_text="For patient context collections, link to specific chat room.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_contexts",
                to="api.chatroom",
            ),
        ),
    ]
