# Generated by Django 5.2.9 - Split migration: Knowledge Bases M2M

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 9: Knowledge Bases Many-to-Many

    Adds the knowledge_bases M2M field to Collection.
    This allows Patient Context collections to link to multiple Knowledge Bases,
    enabling combined context for translations.
    """

    dependencies = [
        ("api", "0008_collection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="knowledge_bases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge base collections to use with this patient context.",
                limit_choices_to={"collection_type": "knowledge_base"},
                related_name="linked_patient_contexts",
                to="api.collection",
            ),
        ),
    ]
