# Generated by Django 4.2.27 on 2026-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_chatmessage_tts_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="completion_model",
            field=models.CharField(default="granite3.3:8b", max_length=100),
        ),
        migrations.AlterField(
            model_name="collection",
            name="embedding_model",
            field=models.CharField(default="nomic-embed-text:latest", max_length=100),
        ),
        migrations.AlterField(
            model_name="collection",
            name="embedding_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("gemini", "Google Gemini"), ("ollama", "Ollama (Local)")],
                default="ollama",
                max_length=100,
            ),
        ),
    ]
