# Generated by Django 4.2.27 on 2026-01-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_collection_completion_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                help_text="For patient context collections, link to specific chat room.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_contexts",
                to="api.chatroom",
            ),
        ),
    ]
